model_name_or_path: /volume/models/Qwen/Qwen2.5-1.5B-Instruct
torch_dtype: bfloat16
output_dir: /volume/models/rag_ckpt/test
dataset_name: "{'path': 'aqweteddy/mrc','revision':'v0'}"
packing: true
dataset_num_proc: 8
use_liger: true
learning_rate: 1e-5
weight_decay: 0.01
optim: paged_adamw_8bit
lr_scheduler_type: cosine
per_device_train_batch_size: 1
max_length: 4096
gradient_checkpointing: true
num_train_epochs: 3
warmup_steps: 100
report_to: wandb
save_only_model: true
save_safetensors: true