model_name_or_path: /volume/models/Yi-1.5-9B-Chat
torch_dtype: bfloat16
dataset: "{'path': 'aqweteddy/mrc','revision':'v0'}"
packing: true
dataset_num_proc: 8
use_liger: true
learning_rate: 1e-5
lr_scheduler_type: cosine
per_device_train_batch_size: 1
max_length: 4096
gradient_checkpointing: true
num_train_epochs: 3
report_to: wandb